{{- if and (not .Values.auth.passwordAuthSecret) .Values.auth.passwordAuth }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "trino.passwordSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "trino.labels" . | nindent 4 }}
data:
{{- if .Values.auth.passwordAuth }}
  pwd.db: {{ .Values.auth.passwordAuth | b64enc }}
{{- end }}
{{- end }}
---
{{- if and (not .Values.auth.groupsAuthSecret) .Values.auth.groups }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "trino.groupsSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "trino.labels" . | nindent 4 }}
data:
{{- if .Values.auth.groups}}
  group.db: {{ .Values.auth.groups | b64enc }}
{{- end }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "trino.fullname" . }}-security-key
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "trino.labels" . | nindent 4 }}
    app.kubernetes.io/component: coordinator
data:
  keystore.jks: {{ .Files.Get "/trino-config/keystore.jks" | b64enc }}
  truststore.jks: {{ .Files.Get "/trino-config/truststore.jks" | b64enc }}
